language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
env:
  - ARGS="--verbose"
  - ARGS="--verbose --features=actix"

script:
  - cargo build $ARGS
  - cargo test $ARGS
